# SPDX-License-Identifier: GPL-2.0
#
# Copyright (c) 2020-2021, Intel Corporation. All rights reserved.
#
# Makefile - IAF client driver for Intel MEI Bus Driver.

subdir-ccflags-y += -I$(backport_srctree)/drivers/misc/mei/

obj-$(CPTCFG_INTEL_MEI_IAF) += mei_iaf.o
