#!/bin/sh
#
# Creates a dkms.conf file

if grep -q CPTCFG_DRM_I915_SELFTEST=y .config; then
	ST=
else
	ST=DEL
fi

if grep -q CPTCFG_DRM_I915_GVT_KVMGT=m .config; then
	KVM=
else
	KVM=DEL
fi

if [ "$ST" = "DEL" ]; then
	GVT_KVMGT=9
elif [ "$KVM" = "DEL" ]; then
	GVT_KVMGT=
else
	GVT_KVMGT=12
fi

PKG_NAME="intel-i915-dkms-prerelease"
PKG_VER="1.0"
REL_NAME="1"
REL_TYPE=""
BUILD_TYPE=""
DEP_PKG_NAME=""
I915_CONFIG=""
DEP_PMT_PKG_NAME="intel-platform-vsec-dkms"

helpFunction()
{
	echo ""
	echo "Usage: $0 -n packagename -v packageversion -r releaseversion -p prerelease/opensource -s buildversion"
	echo -e "\t-n packagename"
	echo -e "\t-v packageversion"
	echo -e "\t-r releaseversion"
	echo -e "\t-p prerelease/opensource"
	echo -e "\t-s buildversion"
	exit 1
}

while getopts "n:v:r:p:s:" opt
do
	case "$opt" in
		n ) PKG_NAME="$OPTARG" ;;
		v ) PKG_VER="$OPTARG" ;;
		r ) REL_NAME="$OPTARG" ;;
		p ) REL_TYPE="$OPTARG" ;;
		s ) BUILD_TYPE="$OPTARG" ;;
		? ) helpFunction ;;
	esac
done

if [ "$REL_TYPE" = "opensource" ]; then
	DEP_PKG_NAME="intel-dmabuf-dkms"
else
	DEP_PKG_NAME="intel-dmabuf-dkms-$REL_TYPE"
fi

if [ "$BUILD_TYPE" != "sp2" ]; then
       I915_CONFIG="i915"
else
       I915_CONFIG="i915_disable_svm"
fi

if [ "$BUILD_TYPE" != "nodrm" ]; then
       NO_DRM=
else
       I915_CONFIG="i915_only"
       NO_DRM=DEL
fi

# We can label the here-doc lines for conditional output to the conf file
#
# Labels:
#  $ST: this line is added only when selftest is enabled
#
sed -e '/^DEL/d' -e 's/^\t*//' <<EOF
	PACKAGE_NAME=$PKG_NAME
	PACKAGE_VERSION=$PKG_VER-$REL_NAME
	AUTOINSTALL="yes"

	BUILT_MODULE_NAME[0]="i915-compat"
	BUILT_MODULE_LOCATION[0]="compat"
	DEST_MODULE_LOCATION[0]="/updates"

	BUILT_MODULE_NAME[1]="i915"
	BUILT_MODULE_LOCATION[1]="drivers/gpu/drm/i915"
	DEST_MODULE_LOCATION[1]="/updates"

	BUILT_MODULE_NAME[2]="i915_spi"
	BUILT_MODULE_LOCATION[2]="drivers/gpu/drm/i915"
	DEST_MODULE_LOCATION[2]="/updates"

	BUILT_MODULE_NAME[3]="iaf"
	BUILT_MODULE_LOCATION[3]="drivers/gpu/drm/i915/fabric"
	DEST_MODULE_LOCATION[3]="/updates"

$NO_DRM	BUILT_MODULE_NAME[4]="intel-gtt"
$NO_DRM	BUILT_MODULE_LOCATION[4]="drivers/char/agp/"
$NO_DRM	DEST_MODULE_LOCATION[4]="/updates"

$NO_DRM	BUILT_MODULE_NAME[5]="drm_kms_helper"
$NO_DRM	BUILT_MODULE_LOCATION[5]="drivers/gpu/drm/"
$NO_DRM	DEST_MODULE_LOCATION[5]="/updates"

$NO_DRM	BUILT_MODULE_NAME[6]="drm"
$NO_DRM	BUILT_MODULE_LOCATION[6]="drivers/gpu/drm/"
$NO_DRM	DEST_MODULE_LOCATION[6]="/updates"

$NO_DRM	BUILT_MODULE_NAME[7]="drm_panel_orientation_quirks"
$NO_DRM	BUILT_MODULE_LOCATION[7]="drivers/gpu/drm/"
$NO_DRM	DEST_MODULE_LOCATION[7]="/updates"

$NO_DRM	BUILT_MODULE_NAME[8]="vgem"
$NO_DRM	BUILT_MODULE_LOCATION[8]="drivers/gpu/drm/vgem"
$NO_DRM	DEST_MODULE_LOCATION[8]="/updates"

$ST	BUILT_MODULE_NAME[20]="test-drm_mm"
$ST	BUILT_MODULE_LOCATION[20]="drivers/gpu/drm/selftests"
$ST	DEST_MODULE_LOCATION[20]="/updates"
$ST
$ST	BUILT_MODULE_NAME[10]="test-drm_cmdline_parser"
$ST	BUILT_MODULE_LOCATION[10]="drivers/gpu/drm/selftests"
$ST	DEST_MODULE_LOCATION[10]="/updates"
$ST
$ST	BUILT_MODULE_NAME[11]="test-drm_modeset"
$ST	BUILT_MODULE_LOCATION[11]="drivers/gpu/drm/selftests"
$ST	DEST_MODULE_LOCATION[11]="/updates"

	
	# Find out how many CPU cores can be use if we pass appropriate -j option to make.
       	# DKMS could use all cores on multicore systems to build the kernel module.
       	num_cpu_cores()
       	{
		if [ -x /usr/bin/nproc ]; then
			np=`nproc`
			if [ "\$np" -le "64" ]; then
				echo "\$np"
			else
				echo "64"
			fi
		else
			echo "1"
		fi
	}
	
	MAKE="export KBUILD_EXTRA_SYMBOLS='\$dkms_tree/$DEP_PKG_NAME/kernel-\$kernelver-x86_64/build/Module.symvers \$dkms_tree/$DEP_PMT_PKG_NAME/kernel-\$kernelver-x86_64/build/Module.symvers'; export LEX=flex; export YACC=bison; cp defconfigs/$I915_CONFIG .config; 'make' -j\$(num_cpu_cores) KLIB=/lib/modules/\$kernelver olddefconfig; 'make' -j\$(num_cpu_cores) KLIB=/lib/modules/\$kernelver BUILD_CONFIG=$BUILD_TYPE"
	CLEAN="export LEX=flex; export YACC=bison; 'make' clean"
EOF
