#!/bin/sh
#
#	Output a RPM spec file to generate intel-i915 binary package
#

PKG_NAME="intel-i915"
PKG_VER="1.0"
REL_NAME="1"
REL_TYPE=""
KER_VER=""
DEP_PKG_NAME=""
DRM_CONFIG="drm"
BUILD_TYPE=""

helpFunction()
{
	echo ""
	echo "Usage: $0 -n packagename -v packageversion -r releaseversion -p prerelease/opensource -s buildversion -k KLIB Path"
	echo -e "\t-n packagename"
	echo -e "\t-v packageversion"
	echo -e "\t-r releaseversion"
	echo -e "\t-p Release Type : prerelease/opensource"
	echo -e "\t-s buildversion"
	echo -e "\t-k KLIB Path"
	exit 1
}

while getopts "n:v:r:p:s:k:" opt
do
	case "$opt" in
		n ) PKG_NAME="$OPTARG" ;;
		v ) PKG_VER="$OPTARG" ;;
		r ) REL_NAME="$OPTARG" ;;
		p ) REL_TYPE="$OPTARG" ;;
		s ) BUILD_TYPE="$OPTARG" ;;
		k )
			KLIB="$OPTARG"
			KER_VER=`basename $KLIB`
			;;
		? ) helpFunction ;; # Print helpFunction
	esac
done

if [ "$BUILD_TYPE" = "sp2" ]; then
	DRM_CONFIG="drm_disable_svm"
fi

sed -e '/^DEL/d' -e 's/^\t*//' <<EOF
	%define package_name $PKG_NAME
	%define version $PKG_VER
	%define release $REL_NAME

	%define _krel $KER_VER
	%define kernel_module_directory /lib/modules
	%define kernel_module_package_moddir updates

	Summary: I915 Backports Kernel Module Package
	Name: %{package_name}
	Version: %{version}
	Release: %{release}
	License: GPL
	Group: System Environment/Base
	BuildArch: x86_64
	Vendor: Intel
	Provides: %{package_name}
	Packager: linux-graphics@intel.com
	Requires: intel-dmabuf
	Conflicts: intel-i915-dkms intel-dmabuf-dkms
	Source0: %{package_name}-%{version}-src.tar.gz
	BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-root/

	%description
	Out of tree prebuilt drm, i915 driver modules.

	%global debug_package %{nil}
	%global _build_id_links none

	%prep
	%setup -q -c
	cp defconfigs/$DRM_CONFIG .config

	%build
	export LEX=flex
	np=`nproc`
	npc=\$(( \$np > 64 ? 64 : \$np ))
	make KLIB=%{kernel_module_directory}/%{_krel} olddefconfig
	make -j\$npc KLIB=%{kernel_module_directory}/%{_krel} BUILD_CONFIG=$BUILD_TYPE

	%install
	if [ "%{buildroot}" != "/" ]; then
		rm -rf %{buildroot}
	fi
	mkdir -p %{buildroot}%{kernel_module_directory}/%{_krel}/%{kernel_module_package_moddir}/%{name}
	find . -name "*.ko" -exec strip -g {} \;
	find . -name "*.ko" -exec xz -z {} \;
	find . -name "*.ko.xz" -exec install -m 0500 {} %{buildroot}%{kernel_module_directory}/%{_krel}/%{kernel_module_package_moddir}/%{name} \;


	%package -n intel-dmabuf
	Summary: DMA-BUF Backports Kernel Module Package
	Group: System Environment/Base
	%description -n intel-dmabuf
	Out of tree prebuilt dmabuf driver modules

	%files
	%defattr(644,root,root)
	%exclude %{kernel_module_directory}/%{_krel}/%{kernel_module_package_moddir}/%{name}/dmabuf*
	%{kernel_module_directory}/%{_krel}/%{kernel_module_package_moddir}/%{name}/

	%files -n intel-dmabuf
	%defattr(644,root,root)
	%{kernel_module_directory}/%{_krel}/%{kernel_module_package_moddir}/%{name}/dmabuf*

	%clean
	if [ "%{buildroot}" != "/" ]; then
		rm -rf %{buildroot}
	echo "clean"
	fi

	%post
	echo "Post Installation"
	depmod -a

	%postun
	echo "Post Uninstalling"
	depmod -a

EOF
