#!/bin/sh
#
#       Output a Install file for debian file
#

PKG_NAME="intel-i915-prerelease"
PKG_VER="1.0"
REL_NAME="1"
REL_TYPE=""
DEP_PKG_NAME=""

helpFunction()
{
	echo ""
	echo "Usage: $0 -n packagename -v packageversion -r releaseversion -p prerelease/opensource"
	echo -e "\t-n packagename"
	echo -e "\t-v packageversion"
	echo -e "\t-r releaseversion"
	echo -e "\t-p Release Type : prerelease/opensource"
	exit 1
}

while getopts "n:v:r:p:" opt
do
	case "$opt" in
		n ) PKG_NAME="$OPTARG" ;;
		v ) PKG_VER="$OPTARG" ;;
		r ) REL_NAME="$OPTARG" ;;
		p ) REL_TYPE="$OPTARG" ;;
		? ) helpFunction ;; # Print helpFunction
	esac
done

DEST="/usr/src/$PKG_NAME-$PKG_VER"

cat <<EOF
Kconfig*		$DEST
Makefile*		$DEST
backport-include	$DEST
compat			$DEST
defconfigs		$DEST
drivers			$DEST
include			$DEST
kconf			$DEST
local-symbols		$DEST
scripts			$DEST
versions		$DEST
EOF
