#!/bin/sh
#
#       Output a readme file for debian package
#

PKG_NAME="intel-i915-prerelease"
PKG_VER="1.0"
REL_NAME="1"
REL_TYPE=""
DEP_PKG_NAME=""

helpFunction()
{
	echo ""
	echo "Usage: $0 -n packagename -v packageversion -r releaseversion -p prerelease/opensource"
	echo -e "\t-n packagename"
	echo -e "\t-v packageversion"
	echo -e "\t-r releaseversion"
	echo -e "\t-p Release Type : prerelease/opensource"
	exit 1
}

while getopts "n:v:r:p:" opt
do
	case "$opt" in
		n ) PKG_NAME="$OPTARG" ;;
		v ) PKG_VER="$OPTARG" ;;
		r ) REL_NAME="$OPTARG" ;;
		p ) REL_TYPE="$OPTARG" ;;
		? ) helpFunction ;; # Print helpFunction
	esac
done

sed -e '/^DEL/d' -e 's/^\t*//' <<EOF
	$PKG_NAME for Debian/Ubuntu
	----------------------------------------

	This package is based on the Linux Backports[1] hosted on git.kernel.org
	and is packaged in deb format for Debian/Ubuntu users.

	[1]: git://git.kernel.org/pub/scm/linux/kernel/git/backports/backports.git
EOF
