#!/bin/sh
#
#       Output a dkms conf file for debian dkms file
#

PKG_NAME="intel-i915-dkms-prerelease"
PKG_VER="1.0"
REL_NAME="1"
REL_TYPE=""
DEP_PKG_NAME=""
DEP_PMT_PKG_NAME="intel-platform-vsec-dkms"

helpFunction()
{
	echo ""
	echo "Usage: $0 -n packagename -v packageversion -r releaseversion -p prerelease/opensource"
	echo -e "\t-n packagename"
	echo -e "\t-v packageversion"
	echo -e "\t-r releaseversion"
	echo -e "\t-p Release Type : prerelease/opensource"
	exit 1
}

while getopts "n:v:r:p:" opt
do
	case "$opt" in
		n ) PKG_NAME="$OPTARG" ;;
		v ) PKG_VER="$OPTARG" ;;
		r ) REL_NAME="$OPTARG" ;;
		p ) REL_TYPE="$OPTARG" ;;
		? ) helpFunction ;; # Print helpFunction
	esac
done

sed -e '/^DEL/d' -e 's/^\t*//' <<EOF
	PACKAGE_NAME="$PKG_NAME"
	PACKAGE_VERSION="$PKG_VER"
	AUTOINSTALL="yes"

	BUILT_MODULE_NAME[0]="compat"
	BUILT_MODULE_LOCATION[0]="compat"
	DEST_MODULE_LOCATION[0]="/updates"

	BUILT_MODULE_NAME[1]="i915"
	BUILT_MODULE_LOCATION[1]="drivers/gpu/drm/i915"
	DEST_MODULE_LOCATION[1]="/updates"

	BUILT_MODULE_NAME[2]="i915_spi"
	BUILT_MODULE_LOCATION[2]="drivers/gpu/drm/i915"
	DEST_MODULE_LOCATION[2]="/updates"

	BUILT_MODULE_NAME[3]="iaf"
	BUILT_MODULE_LOCATION[3]="drivers/gpu/drm/i915/fabric"
	DEST_MODULE_LOCATION[3]="/updates"

	# Find out how many CPU cores can be use if we pass appropriate -j option to make.
	# DKMS could use all cores on multicore systems to build the kernel module.
	num_cpu_cores()
	{
	  if [ -x /usr/bin/nproc ]; then
		np=`nproc`
		if [ "\$np" -le "64" ]; then
			echo "\$np"
		else
			echo "64"
		fi
	  else
	    echo "1"
	  fi
	}

	# Here is where we could specify use of the defconfig. Right now it uses the kernel configuration from /usr/src/
	MAKE="export KBUILD_EXTRA_SYMBOLS='\$dkms_tree/$DEP_PMT_PKG_NAME/kernel-\$kernelver-x86_64/build/Module.symvers'; cp defconfigs/i915 .config; 'make' -j\$(num_cpu_cores) KLIB=/lib/modules/\$kernelver olddefconfig; 'make' -j\$(num_cpu_cores) KLIB=/lib/modules/\$kernelver"
	CLEAN="'make' clean"
EOF
