#!/bin/sh
#
# Creates a dkms.conf file

if grep -q CPTCFG_DRM_I915_SELFTEST=y .config; then
	ST=
else
	ST=DEL
fi

if [ "$1"="" ]; then
	PKG_NAME="$1"
else
	PKG_NAME="intel-gpgpu-dkms-prerelease"
fi

if [ "$2"="" ]; then
	PKG_VER="$2"
else
	PKG_VER="1.0"
fi

if [ "$3"="" ]; then
	REL_NAME="$3"
else
	REL_NAME="1"
fi

# We can label the here-doc lines for conditional output to the conf file
#
# Labels:
#  $ST: this line is added only when selftest is enabled
#
sed -e '/^DEL/d' -e 's/^\t*//' <<EOF
	PACKAGE_NAME=$PKG_NAME
	PACKAGE_VERSION=$PKG_VER-$REL_NAME
	AUTOINSTALL="yes"

	BUILT_MODULE_NAME[0]="i915-compat"
	BUILT_MODULE_LOCATION[0]="compat"
	DEST_MODULE_LOCATION[0]="/updates"

	BUILT_MODULE_NAME[1]="drm_kms_helper"
	BUILT_MODULE_LOCATION[1]="drivers/gpu/drm/"
	DEST_MODULE_LOCATION[1]="/updates"

	BUILT_MODULE_NAME[2]="drm"
	BUILT_MODULE_LOCATION[2]="drivers/gpu/drm/"
	DEST_MODULE_LOCATION[2]="/updates"

	BUILT_MODULE_NAME[3]="drm_panel_orientation_quirks"
	BUILT_MODULE_LOCATION[3]="drivers/gpu/drm/"
	DEST_MODULE_LOCATION[3]="/updates"

	BUILT_MODULE_NAME[4]="i915"
	BUILT_MODULE_LOCATION[4]="drivers/gpu/drm/i915"
	DEST_MODULE_LOCATION[4]="/updates"

	BUILT_MODULE_NAME[5]="vgem"
	BUILT_MODULE_LOCATION[5]="drivers/gpu/drm/vgem"
	DEST_MODULE_LOCATION[5]="/updates"

	BUILT_MODULE_NAME[6]="i915_spi"
	BUILT_MODULE_LOCATION[6]="drivers/gpu/drm/i915"
	DEST_MODULE_LOCATION[6]="/updates"
	
	BUILT_MODULE_NAME[7]="iaf"
	BUILT_MODULE_LOCATION[7]="drivers/gpu/drm/i915/fabric"
	DEST_MODULE_LOCATION[7]="/updates"
	
	BUILT_MODULE_NAME[8]="dmabuf"
	BUILT_MODULE_LOCATION[8]="drivers/dma-buf"
	DEST_MODULE_LOCATION[8]="/updates"

	BUILT_MODULE_NAME[9]="kvmgt"
	BUILT_MODULE_LOCATION[9]="drivers/gpu/drm/i915/gvt"
	DEST_MODULE_LOCATION[9]="/updates"

$ST	BUILT_MODULE_NAME[10]="test-drm_mm"
$ST	BUILT_MODULE_LOCATION[10]="drivers/gpu/drm/selftests"
$ST	DEST_MODULE_LOCATION[10]="/updates"
$ST
$ST	BUILT_MODULE_NAME[11]="test-drm_cmdline_parser"
$ST	BUILT_MODULE_LOCATION[11]="drivers/gpu/drm/selftests"
$ST	DEST_MODULE_LOCATION[11]="/updates"
$ST
$ST	BUILT_MODULE_NAME[12]="test-drm_modeset"
$ST	BUILT_MODULE_LOCATION[12]="drivers/gpu/drm/selftests"
$ST	DEST_MODULE_LOCATION[12]="/updates"
$ST
$ST	BUILT_MODULE_NAME[13]="dmabuf_selftests"
$ST	BUILT_MODULE_LOCATION[13]="drivers/dma-buf"
$ST	DEST_MODULE_LOCATION[13]="/updates"
$ST
	# Find out how many CPU cores can be use if we pass appropriate -j option to make.
	# DKMS could use all cores on multicore systems to build the kernel module.
	num_cpu_cores()
	{
	  if [ -x /usr/bin/nproc ]; then
	    nproc
	  else
	    echo "1"
	  fi
	}

	MAKE="export LEX=flex; cp defconfigs/drm .config; 'make' -j\$(num_cpu_cores) KLIB=/lib/modules/\$kernelver olddefconfig; 'make' -j\$(num_cpu_cores) KLIB=/lib/modules/\$kernelver"
	CLEAN="'make' clean"
EOF
