#!/bin/sh
#
#	Output a simple RPM spec file.
#	This version assumes a minimum of RPM 4.0.3.
#
#	The only gothic bit here is redefining install_post to avoid
#	stripping the symbols from files in the kernel which we want
#
#	Patched for non-x86 by Opencon (L) 2002 <opencon@rio.skydome.net>
#

# how we were called determines which rpms we build and how we build them
if [ "$1" = prebuilt ]; then
	S=DEL
	MAKE="$MAKE -f $srctree/Makefile"
else
	S=
fi

if grep -q CPTCFG_MODULES=y .config; then
	M=
else
	M=DEL
fi

KERNELRELEASE=$(uname -r)

# We can label the here-doc lines for conditional output to the spec file
#
# Labels:
#  $S: this line is enabled only when building source package
#  $M: this line is enabled only when CPTCFG_MODULES is enabled
sed -e '/^DEL/d' -e 's/^\t*//' <<EOF
	Name: backport-modules
	Summary: Linux kernel backports package
	Version: $KERNELRELEASE
	Release: $(cat .version 2>/dev/null || echo 1)
	License: GPLv2
	Vendor: Intel
	URL: https://backports.wiki.kernel.org

	%description
	Linux kernel backports package, provides backport support for drivers from newer kernels
	down to older kernels.This package backports the DRM and GPU subsystems.
	This package provides the latest Linux kernel subsystem enhancements for kernels 3.10 and above.

$S	%prep
$S	%setup -q
$S
	%install
	mkdir -p %{buildroot}/lib/modules/$KERNELRELEASE/kernel/drivers/gpu/drm
	mkdir -p %{buildroot}/lib/modules/$KERNELRELEASE/kernel/drivers/gpu/drm/i915
	mkdir -p %{buildroot}/lib/modules/$KERNELRELEASE/kernel/drivers/gpu/drm/selftests
	mkdir -p %{buildroot}/lib/modules/$KERNELRELEASE/kernel/drivers/gpu/drm/vgem
	cp compat/i915-compat.ko %{buildroot}/lib/modules/$KERNELRELEASE/kernel/drivers/gpu/drm/
	cp drivers/gpu/drm/drm_kms_helper.ko drivers/gpu/drm/drm.ko drivers/gpu/drm/drm_panel_orientation_quirks.ko %{buildroot}/lib/modules/$KERNELRELEASE/kernel/drivers/gpu/drm/
	cp drivers/gpu/drm/i915/i915.ko %{buildroot}/lib/modules/$KERNELRELEASE/kernel/drivers/gpu/drm/i915/
	cp drivers/gpu/drm/selftests/*.ko %{buildroot}/lib/modules/$KERNELRELEASE/kernel/drivers/gpu/drm/selftests
	cp drivers/gpu/drm/vgem/vgem.ko %{buildroot}/lib/modules/$KERNELRELEASE/kernel/drivers/gpu/drm/vgem

	%clean
	rm -rf %{buildroot}

	%files
	%defattr (-, root, root)
$M	/lib/modules/$KERNELRELEASE

EOF
