# SPDX-License-Identifier: GPL-2.0-only
obj-$(CPTCFG_DRM_DW_HDMI) += dw-hdmi.o
obj-$(CPTCFG_DRM_DW_HDMI_AHB_AUDIO) += dw-hdmi-ahb-audio.o
obj-$(CPTCFG_DRM_DW_HDMI_I2S_AUDIO) += dw-hdmi-i2s-audio.o
obj-$(CPTCFG_DRM_DW_HDMI_CEC) += dw-hdmi-cec.o

obj-$(CPTCFG_DRM_DW_MIPI_DSI) += dw-mipi-dsi.o
